# Generated by Django 3.0.7 on 2020-06-20 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request')], max_length=7)),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
