# Generated by Django 3.0.7 on 2020-07-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.CharField(choices=[('bugzapp', 'BugzApp'), ('peakwellness', 'Peak Wellness'), ('simongame', 'Simon Game'), ('geminerald', 'Geminerald'), ('test', 'test')], default='test', max_length=20),
        ),
    ]
